export const AppointmentsTypes = {
  LOAD_APPOINTMENTS_AVAIBLE_REQUEST: 'LOAD_APPOINTMENTS_AVAIBLE_REQUEST',
  LOAD_APPOINTMENTS_AVAIBLE_SUCCESS: 'LOAD_APPOINTMENTS_AVAIBLE_SUCCESS',
  SELECTED_DATE_APPOINTMENT: 'SELECTED_DATE_APPOINTMENT',
  REMOVE_DATE_APPOINTMENT: 'REMOVE_DATE_APPOINTMENT',

  LOAD_HOURS_APPOINTMENTS_AVAIBLE_REQUEST:
    'LOAD_HOURS_APPOINTMENTS_AVAIBLE_REQUEST',
  LOAD_HOURS_APPOINTMENTS_AVAIBLE_SUCCESS:
    'LOAD_HOURS_APPOINTMENTS_AVAIBLE_SUCCESS',

  SELECTED_HOUR_APPOINTMENT: 'SELECTED_HOUR_APPOINTMENT',
  REMOVE_HOUR_APPOINTMENT: 'REMOVE_HOUR_APPOINTMENT',
}
